from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    if old not in text:
        raise RuntimeError(f"missing anchor: {label}")
    return text.replace(old, new, 1)


surface_path = Path("native/src/world/PlanetSurface.cpp")
s = surface_path.read_text()

old_ranges = '''    const double rangeRidgeA = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0xD6E8FEB86659FD93ULL, w, 34.0, 5));\n    const double rangeRidgeB = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0xA5A3564E27F8862FULL, w, 82.0, 4));\n    const double rangeRidgeC = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0x9E3779B185EBCA87ULL, w, 210.0, 3));\n    const double rangeMask = smooth01(0.07, 0.66, geomorph.mountain) * geomorphLandness;\n    const double ridgeCoreA = std::pow(smooth01(0.30, 0.86, rangeRidgeA), 2.15);\n    const double ridgeCoreB = std::pow(smooth01(0.34, 0.88, rangeRidgeB), 1.90);\n    const double ridgeCoreC = std::pow(smooth01(0.40, 0.91, rangeRidgeC), 1.65);\n\n    // R4 relief V5: the global geomorph bake owns the mountain-belt location.  These\n    // signed bands reconstruct crests AND inter-range valleys instead of lifting a whole\n    // orogenic province into one high slab.\n    const double rangeRelief = rangeMask * (\n        0.260 * (ridgeCoreA - 0.42)\n        + 0.160 * (ridgeCoreB - 0.38)\n        + 0.090 * (ridgeCoreC - 0.34));\n    const double interRangeValley = rangeMask * std::pow(\n        1.0 - std::clamp(std::max(ridgeCoreA, ridgeCoreB * 0.72), 0.0, 1.0), 2.2);\n    elevation += maxLand * rangeRelief;\n    elevation -= maxLand * 0.085 * interRangeValley;\n\n    // Post-bake highland authority: elevated continental interiors that are not mountain\n    // cores.  This is what the plateau/highland capture and material logic now query.\n    const double globalHighland = geomorphLandness\n        * smooth01(900.0, 2400.0, geomorph.elevationMeters)\n        * (1.0 - smooth01(0.22, 0.68, geomorph.mountain));'''

new_ranges = '''    // R6 mountain shape: R5 proved that 190-1200 km ridges still read as one giant slope\n    // from a player camera. Reconstruct the tectonic authority at 20-160 km wavelengths so\n    // individual massifs, passes and inter-range valleys exist inside the same orogenic belt.\n    const double rangeRidgeA = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0xD6E8FEB86659FD93ULL, w, 260.0, 5));\n    const double rangeRidgeB = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0xA5A3564E27F8862FULL, w, 760.0, 4));\n    const double rangeRidgeC = 1.0 - std::abs(fbmSurface(\n        definition.seed ^ 0x9E3779B185EBCA87ULL, w, 1900.0, 3));\n    const double rangeMask = smooth01(0.05, 0.56, geomorph.mountain) * geomorphLandness;\n    const double ridgeCoreA = std::pow(smooth01(0.28, 0.86, rangeRidgeA), 2.00);\n    const double ridgeCoreB = std::pow(smooth01(0.32, 0.89, rangeRidgeB), 1.92);\n    const double ridgeCoreC = std::pow(smooth01(0.38, 0.93, rangeRidgeC), 1.72);\n    const double summitCore = rangeMask * std::pow(\n        std::clamp(std::max(ridgeCoreB, ridgeCoreC * 0.92), 0.0, 1.0), 2.35);\n    const double rangeRelief = rangeMask * (\n        0.160 * (ridgeCoreA - 0.30)\n        + 0.100 * (ridgeCoreB - 0.26)\n        + 0.060 * (ridgeCoreC - 0.22));\n    const double interRangeValley = rangeMask * std::pow(\n        1.0 - std::clamp(std::max(ridgeCoreA, ridgeCoreB * 0.82), 0.0, 1.0), 2.0);\n    elevation += maxLand * (rangeRelief + 0.220 * summitCore);\n    elevation -= maxLand * 0.075 * interRangeValley;\n\n    // R6 plateau shape: a highland must have a broad top and a readable escarpment.\n    // Continental-elevation authority still decides where highlands may exist; a regional\n    // band-limited mask then flattens only their interiors toward a shelf level and leaves\n    // a comparatively sharp rim at the mask boundary.\n    const double globalHighland = geomorphLandness\n        * smooth01(900.0, 2400.0, geomorph.elevationMeters)\n        * (1.0 - smooth01(0.22, 0.68, geomorph.mountain));\n    const double plateauMacro = 0.5 + 0.5 * fbmSurface(\n        definition.seed ^ 0x4A7484AA6EA6E483ULL, w, 120.0, 4);\n    const double plateauMeso = 0.5 + 0.5 * fbmSurface(\n        definition.seed ^ 0x5CB0A9DCBD41FBD4ULL, w, 330.0, 3);\n    const double plateauSignal = plateauMacro * 0.74 + plateauMeso * 0.26;\n    const double plateauBody = globalHighland * smooth01(0.57, 0.69, plateauSignal);\n    const double plateauTopNoise = fbmSurface(\n        definition.seed ^ 0x76F988DA831153B5ULL, w, 520.0, 2);\n    const double plateauShelf = 2350.0 + 260.0 * plateauTopNoise;\n    const double plateauBlend = 0.72 * plateauBody;\n    elevation = elevation * (1.0 - plateauBlend) + plateauShelf * plateauBlend;\n    elevation += maxLand * 0.030 * plateauBody;'''

s = replace_once(s, old_ranges, new_ranges, "R6 mountain/highland shape")
s = replace_once(
    s,
    "    sample.plateau = std::max(plateau, globalHighland);",
    "    sample.plateau = std::max(plateau, plateauBody);",
    "R6 plateau authority",
)
surface_path.write_text(s)


main_path = Path("native/src/app/Main.cpp")
m = main_path.read_text()

old_capture_modes = '''            if (captureMode == "mountain") {\n                if (terrain.mountain < 0.20 || aboveSea < 900.0) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 62000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                if (relief < 900.0) continue;\n                captureScore += terrain.mountain * 3.8 + relief / 720.0\n                    + aboveSea / 5200.0 + terrain.canyon * 0.8;\n            } else if (captureMode == "river") {\n                if (terrain.river < 0.18) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 10500.0);\n                const double valleyDepth = std::max(0.0, r.meanElevation - aboveSea);\n                captureScore += terrain.river * 6.0 + valleyDepth / 120.0\n                    + terrain.canyon * 1.8\n                    - std::max(0.0, aboveSea - 1800.0) / 1800.0;\n            } else if (captureMode == "coast") {\n                if (std::abs(aboveSea) > 520.0 || terrain.coastalCliff < 0.06) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 18000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                const double crossesSea = r.minElevation < -15.0 ? 1.0 : 0.0;\n                captureScore += terrain.coastalCliff * 4.8 + relief / 240.0\n                    + crossesSea * 2.2 - std::abs(aboveSea - 90.0) / 650.0;\n            } else if (captureMode == "highland") {\n                if (terrain.plateau < 0.18 || aboveSea < 950.0 || aboveSea > 4300.0) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 52000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                captureScore += terrain.plateau * 4.8 + aboveSea / 1900.0\n                    + std::min(relief, 2600.0) / 1300.0 - terrain.mountain * 1.3;\n            }'''
new_capture_modes = '''            if (captureMode == "mountain") {\n                if (terrain.mountain < 0.18 || aboveSea < 1500.0) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 36000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                if (relief < 1800.0) continue;\n                captureScore += terrain.mountain * 4.2 + relief / 460.0\n                    + aboveSea / 4200.0 + terrain.canyon * 0.7;\n            } else if (captureMode == "river") {\n                if (terrain.river < 0.18) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 10500.0);\n                const double valleyDepth = std::max(0.0, r.meanElevation - aboveSea);\n                captureScore += terrain.river * 6.0 + valleyDepth / 120.0\n                    + terrain.canyon * 1.8\n                    - std::max(0.0, aboveSea - 1800.0) / 1800.0;\n            } else if (captureMode == "coast") {\n                if (aboveSea < 18.0 || aboveSea > 280.0 || terrain.coastalCliff < 0.08) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 12000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                if (r.minElevation > -12.0 || relief < 300.0) continue;\n                captureScore += terrain.coastalCliff * 5.4 + relief / 170.0\n                    - std::abs(aboveSea - 120.0) / 320.0;\n            } else if (captureMode == "highland") {\n                if (terrain.plateau < 0.40 || aboveSea < 1600.0 || aboveSea > 3300.0) continue;\n                const LocalReliefStats r = sampleLocalRelief(planet, d, 30000.0);\n                const double relief = r.maxElevation - r.minElevation;\n                if (relief < 650.0) continue;\n                captureScore += terrain.plateau * 5.6 + aboveSea / 1800.0\n                    + std::min(relief, 2400.0) / 900.0 - terrain.mountain * 1.6;\n            }'''
m = replace_once(m, old_capture_modes, new_capture_modes, "R6 capture target metrics")

old_radii = '''    // R5 capture geometry: close low-angle evidence stays inside useful terrain LODs.\n    const std::array<double, 5> mountainRadii{18000.0, 26000.0, 38000.0, 52000.0, 70000.0};\n    const std::array<double, 5> highlandRadii{12000.0, 18000.0, 26000.0, 36000.0, 50000.0};\n    const std::array<double, 5> coastRadii{1800.0, 3000.0, 4500.0, 6500.0, 9000.0};\n    const std::array<double, 5> riverRadii{1200.0, 1800.0, 2600.0, 3600.0, 5200.0};'''
new_radii = '''    // R6 capture geometry: every target is kept inside the fine/mid clipmap range and\n    // mountains/highlands are viewed from a lower flank rather than from kilometres overhead.\n    const std::array<double, 5> mountainRadii{8000.0, 12000.0, 18000.0, 26000.0, 38000.0};\n    const std::array<double, 5> highlandRadii{8000.0, 12000.0, 18000.0, 26000.0, 36000.0};\n    const std::array<double, 5> coastRadii{2500.0, 4500.0, 7000.0, 11000.0, 16000.0};\n    const std::array<double, 5> riverRadii{1200.0, 1800.0, 2600.0, 3600.0, 5200.0};'''
m = replace_once(m, old_radii, new_radii, "R6 capture radii")

old_scores = '''            if (mode == "coast") {\n                if (!terrain.submerged(planet)) continue;\n                score = std::abs(terrain.elevationMeters + 30.0) * 0.06\n                    + std::abs(standOffMeters - 4500.0) * 0.020;\n            } else if (mode == "river") {\n                if (terrain.submerged(planet) || terrain.river > 0.16) continue;\n                score = std::abs(terrain.elevationMeters - targetElevation) * 0.18\n                    + terrain.river * 2200.0\n                    + std::abs(standOffMeters - 2600.0) * 0.035;\n            } else if (mode == "mountain") {\n                if (terrain.submerged(planet)) continue;\n                score = terrain.elevationMeters * 1.35\n                    + terrain.mountain * 1350.0\n                    + std::abs(standOffMeters - 32000.0) * 0.014;\n            } else {\n                if (terrain.submerged(planet)) continue;\n                score = terrain.elevationMeters * 0.95\n                    + terrain.mountain * 1050.0\n                    + std::abs(standOffMeters - 24000.0) * 0.018;\n            }'''
new_scores = '''            if (mode == "coast") {\n                if (!terrain.submerged(planet)) continue;\n                score = std::abs(terrain.elevationMeters + 22.0) * 0.05\n                    + std::abs(standOffMeters - 7000.0) * 0.018;\n            } else if (mode == "river") {\n                if (terrain.submerged(planet) || terrain.river > 0.16) continue;\n                score = std::abs(terrain.elevationMeters - targetElevation) * 0.18\n                    + terrain.river * 2200.0\n                    + std::abs(standOffMeters - 2600.0) * 0.035;\n            } else if (mode == "mountain") {\n                if (terrain.submerged(planet)) continue;\n                score = terrain.elevationMeters * 1.45\n                    + terrain.mountain * 1900.0\n                    + std::abs(standOffMeters - 18000.0) * 0.020;\n            } else {\n                if (terrain.submerged(planet)) continue;\n                score = terrain.elevationMeters * 1.05\n                    + terrain.plateau * 1650.0\n                    + terrain.mountain * 1200.0\n                    + std::abs(standOffMeters - 18000.0) * 0.020;\n            }'''
m = replace_once(m, old_scores, new_scores, "R6 vantage scores")

old_lifts = '''            const double targetLift = captureMode == "mountain" ? 420.0\n                : (captureMode == "highland" ? 180.0 : (captureMode == "coast" ? 85.0 : 28.0));\n            const double cameraLift = captureMode == "mountain" ? 220.0\n                : (captureMode == "highland" ? 240.0\n                : (captureMode == "coast" ? 95.0 : 90.0));'''
new_lifts = '''            const double targetLift = captureMode == "mountain" ? 260.0\n                : (captureMode == "highland" ? 120.0 : (captureMode == "coast" ? 80.0 : 28.0));\n            const double cameraLift = captureMode == "mountain" ? 180.0\n                : (captureMode == "highland" ? 180.0\n                : (captureMode == "coast" ? 80.0 : 90.0));'''
m = replace_once(m, old_lifts, new_lifts, "R6 camera lifts")

main_path.write_text(m)
print("R6 landform-shape materialization complete")
