from pathlib import Path

path = Path("native/src/app/Main.cpp")
text = path.read_text(encoding="utf-8")
anchor = '        const std::uint32_t moonId = celestial.addBody(luna);\n'
insert = '''        const std::uint32_t moonId = celestial.addBody(luna);\n\n        // Deterministic evidence camera. This remains the real PlanetCamera and the real Vulkan\n        // renderer; only its initial pose is selected explicitly so CI cannot accidentally stare at\n        // empty sky after synthetic mouse input. Production runs do not set this environment flag.\n        if (const char* aerialEnv = std::getenv("VF_CAPTURE_AERIAL");\n            aerialEnv != nullptr && std::string_view{aerialEnv} == "1") {\n            double aerialAltitude = 5200.0;\n            if (const char* altitudeEnv = std::getenv("VF_CAPTURE_ALTITUDE_METERS");\n                altitudeEnv != nullptr && *altitudeEnv != '\\0') {\n                try { aerialAltitude = std::clamp(std::stod(altitudeEnv), 800.0, 18000.0); }\n                catch (...) { aerialAltitude = 5200.0; }\n            }\n            const double localSurfaceRadius = vf::planetSurfaceRadius(planet, spawnDirection);\n            const glm::dvec3 localOffset = spawnDirection * (localSurfaceRadius + aerialAltitude);\n            const glm::dvec3 worldOffset = aster.orientation * localOffset;\n            const glm::dvec3 worldUp = safeNormalize(worldOffset, spawnDirection);\n            const glm::dvec3 angularVelocity = safeNormalize(aster.spinAxis, {0.0, 1.0, 0.0})\n                * aster.spinRateRadPerSecond;\n            camera.setExternalWorldState(\n                aster.position + worldOffset,\n                aster.linearVelocity + glm::cross(angularVelocity, worldOffset),\n                false);\n            const glm::dvec3 tangent = stableTangent(worldUp);\n            camera.setViewDirectionWorld(\n                safeNormalize(tangent * 0.58 - worldUp * 0.82, -worldUp),\n                worldUp);\n            std::cout << "R23 deterministic aerial camera altitude="\n                      << aerialAltitude << " m\\n";\n        }\n\n        if (const char* celestialTargetEnv = std::getenv("VF_CELESTIAL_TARGET");\n            celestialTargetEnv != nullptr && *celestialTargetEnv != '\\0') {\n            const std::string_view celestialTarget{celestialTargetEnv};\n            if (celestialTarget == "sun") {\n                camera.setViewDirectionWorld(\n                    sun.position - camera.position(), camera.up());\n                std::cout << "R23 celestial target: sun\\n";\n            } else if (celestialTarget == "moon") {\n                camera.setViewDirectionWorld(\n                    luna.position - camera.position(), camera.up());\n                std::cout << "R23 celestial target: moon\\n";\n            }\n        }\n'''
if anchor not in text:
    raise SystemExit("R23 celestial/aerial target patch anchor missing")
text = text.replace(anchor, insert, 1)
path.write_text(text, encoding="utf-8")
print("R23 deterministic evidence camera patch applied")
