from pathlib import Path

shader_path = Path('native/shaders/planet.slang')
text = shader_path.read_text(encoding='utf-8')
marker = '// R24_SHADER_THROUGHPUT_RESCUE_V1'
if marker in text:
    print('R24 shader throughput rescue already materialized')
    raise SystemExit(0)

old = '''    float3 terrainAerialTransmittance : TEXCOORD7;\n    float3 terrainAerialInscatter : TEXCOORD8;\n};'''
new = '''    float3 terrainAerialTransmittance : TEXCOORD7;\n    float3 terrainAerialInscatter : TEXCOORD8;\n    // R24_SHADER_THROUGHPUT_RESCUE_V1\n    // Terrain lighting is low-frequency relative to the current ~70 m LOD cells. Evaluate the\n    // expensive normal/material/irradiance terms once per vertex and perspective-interpolate them.\n    float3 terrainDirectDiffuse : TEXCOORD9;\n    float3 terrainAmbientDiffuse : TEXCOORD10;\n    float terrainNoL : TEXCOORD11;\n    float3 terrainShadowNdc : TEXCOORD12;\n    float terrainShadowEligible : TEXCOORD13;\n};'''
if old not in text:
    raise SystemExit('VertexOutput anchor changed')
text = text.replace(old, new, 1)

old = '''    float3 worldPosition = rotateByQuaternion(input.position, gPush.data3);\n    float3 worldNormal = normalize(rotateByQuaternion(input.normal, gPush.data3));\n    float3 relativePosition = worldPosition - gPush.data0.xyz;'''
new = '''    float3 worldPosition = rotateByQuaternion(input.position, gPush.data3);\n    float3 worldNormal = normalize(rotateByQuaternion(input.normal, gPush.data3));\n    // Water wave slope is geometric low-frequency data. Doing four sin/cos operations once per\n    // vertex avoids repeating them for every transparent fragment while retaining the same wave\n    // field and continuously interpolated normal.\n    const bool vertexWaterMaterial = input.material.x < -0.5;\n    if (vertexWaterMaterial)\n    {\n        float2 p = input.position.xz * 0.00175;\n        float2 waveSlope = float2(\n            sin(p.x * 1.00 + p.y * 0.57) + 0.48 * sin(p.x * 2.31 - p.y * 1.73),\n            cos(p.y * 1.07 - p.x * 0.61) + 0.44 * cos(p.y * 2.19 + p.x * 1.51));\n        worldNormal = normalize(worldNormal + float3(waveSlope.x, 0.0, waveSlope.y) * 0.055);\n    }\n    float3 relativePosition = worldPosition - gPush.data0.xyz;'''
if old not in text:
    raise SystemExit('vertexMain world normal anchor changed')
text = text.replace(old, new, 1)

old = '''    output.terrainAerialTransmittance = float3(1.0, 1.0, 1.0);\n    output.terrainAerialInscatter = float3(0.0, 0.0, 0.0);\n    if (terrainMaterial)\n    {'''
new = '''    output.terrainAerialTransmittance = float3(1.0, 1.0, 1.0);\n    output.terrainAerialInscatter = float3(0.0, 0.0, 0.0);\n    output.terrainDirectDiffuse = float3(0.0, 0.0, 0.0);\n    output.terrainAmbientDiffuse = float3(0.0, 0.0, 0.0);\n    output.terrainNoL = 0.0;\n    output.terrainShadowNdc = float3(0.0, 0.0, 0.0);\n    output.terrainShadowEligible = 0.0;\n    if (terrainMaterial)\n    {\n        float3 n = worldNormal;\n        float3 l = normalize(gPush.data1.xyz);\n        float noL = saturate(dot(n, l));\n        float3 baseColor = max(input.color, 0.0);\n        float macro = output.terrainMacro;\n        float localSlope = saturate(1.0 - n.y);\n        baseColor *= 0.95 + macro * 0.10;\n        baseColor = lerp(\n            baseColor, baseColor * float3(1.035, 1.005, 0.945),\n            smoothstep(0.62, 0.86, macro) * 0.14);\n        baseColor = lerp(\n            baseColor, baseColor * float3(0.89, 0.92, 0.90),\n            smoothstep(0.32, 0.72, localSlope) * 0.24);\n\n        float3 stellar = max(gPush.data2.rgb, 0.0) * max(gPush.data2.a, 0.0);\n        output.terrainDirectDiffuse = baseColor * (0.96 / PI) * noL * stellar;\n        float skyWeight = saturate(n.y * 0.5 + 0.5);\n        float3 skyIrradiance = max(gScene.skyAmbientExposure.rgb, 0.0)\n            * (0.28 + 0.72 * skyWeight);\n        float3 groundIrradiance = max(gScene.groundAmbientShadowTexel.rgb, 0.0)\n            * saturate(-n.y * 0.5 + 0.5);\n        output.terrainAmbientDiffuse = baseColor * (skyIrradiance + groundIrradiance) * 0.96;\n        output.terrainNoL = noL;\n\n        // The light projection is orthographic for the local contact map. Reject terrain vertices\n        // outside the tiny 250 m atlas here so aerial terrain fragments never execute PCF setup.\n        if (noL > 0.0001 && output.shadowPosition.w > 0.0)\n        {\n            float3 shadowNdc = output.shadowPosition.xyz / output.shadowPosition.w;\n            float2 shadowUv = shadowNdc.xy * 0.5 + 0.5;\n            bool insideShadow = all(shadowUv >= 0.0) && all(shadowUv <= 1.0)\n                && shadowNdc.z >= 0.0 && shadowNdc.z <= 1.0;\n            output.terrainShadowNdc = shadowNdc;\n            output.terrainShadowEligible = insideShadow ? 1.0 : 0.0;\n        }'''
if old not in text:
    raise SystemExit('terrain vertex atmosphere anchor changed')
text = text.replace(old, new, 1)

# Remove per-fragment procedural water normal; vertexMain now supplies the same field.
old = '''    if (waterMaterial)\n    {\n        float2 p = input.objectPosition.xz * 0.00175;\n        float2 waveSlope = float2(\n            sin(p.x * 1.00 + p.y * 0.57) + 0.48 * sin(p.x * 2.31 - p.y * 1.73),\n            cos(p.y * 1.07 - p.x * 0.61) + 0.44 * cos(p.y * 2.19 + p.x * 1.51));\n        n = normalize(n + float3(waveSlope.x, 0.0, waveSlope.y) * 0.055);\n    }\n\n'''
if old not in text:
    raise SystemExit('water fragment wave anchor changed')
text = text.replace(old, '', 1)

old = '''float3 evaluateTerrainFast(VertexOutput input)\n{\n    float3 n = normalize(input.normal);\n    float3 l = normalize(gPush.data1.xyz);\n    float noL = saturate(dot(n, l));\n    float3 baseColor = max(input.color, 0.0);\n\n    // PlanetSurface/LodMeshBuilder already bakes biome/elevation variation into vertex.color. One\n    // broad sample prevents flat color blocks without rebuilding multi-octave material noise.\n    float macro = input.terrainMacro;\n    float localSlope = saturate(1.0 - n.y);\n    baseColor *= 0.95 + macro * 0.10;\n    baseColor = lerp(\n        baseColor, baseColor * float3(1.035, 1.005, 0.945),\n        smoothstep(0.62, 0.86, macro) * 0.14);\n    baseColor = lerp(\n        baseColor, baseColor * float3(0.89, 0.92, 0.90),\n        smoothstep(0.32, 0.72, localSlope) * 0.24);\n\n    // Common dielectrics reflect about 4% at normal incidence. For this deliberately high-roughness\n    // terrain path reserve that energy and spend the remaining 96% on a Lambert lobe. This removes\n    // the per-pixel half-vector normalization, Schlick pow, GGX D term, two Smith G terms, reflect\n    // and ambient-specular work from the overwhelmingly largest opaque material.\n    float shadow = noL > 0.0001 ? shadowVisibility(input.shadowPosition, noL) : 1.0;\n    float3 stellar = max(gPush.data2.rgb, 0.0) * max(gPush.data2.a, 0.0);\n    float3 directDiffuse = baseColor * (0.96 / PI) * noL * stellar * shadow;\n\n    float skyWeight = saturate(n.y * 0.5 + 0.5);\n    float3 skyIrradiance = max(gScene.skyAmbientExposure.rgb, 0.0) * (0.28 + 0.72 * skyWeight);\n    float3 groundIrradiance = max(gScene.groundAmbientShadowTexel.rgb, 0.0)\n        * saturate(-n.y * 0.5 + 0.5);\n    float3 ambientDiffuse = baseColor * (skyIrradiance + groundIrradiance) * 0.96;\n    return directDiffuse + ambientDiffuse;\n}\n'''
new = '''float shadowVisibilityPrepared(float3 ndc, float noL)\n{\n    float2 uv = ndc.xy * 0.5 + 0.5;\n    float texel = max(gScene.groundAmbientShadowTexel.w, 1.0 / 4096.0);\n    float bias = 0.000012 + 0.000055 * (1.0 - saturate(noL));\n    static const float2 offsets[3] = {\n        float2(0.0, 0.0), float2(0.78, 0.31), float2(-0.78, -0.31),\n    };\n    float visible = 0.0;\n    [unroll]\n    for (int i = 0; i < 3; ++i)\n    {\n        float stored = gShadowMap.SampleLevel(gShadowSampler, uv + offsets[i] * texel, 0.0);\n        visible += ndc.z - bias <= stored ? 1.0 : 0.0;\n    }\n    return visible / 3.0;\n}\n\nfloat3 evaluateTerrainFast(VertexOutput input)\n{\n    // Direct + ambient lighting was evaluated per vertex. In the common aerial case every vertex\n    // is outside the local contact-shadow atlas, so this fragment path is interpolation + add only.\n    float shadow = input.terrainShadowEligible > 0.5\n        ? shadowVisibilityPrepared(input.terrainShadowNdc, input.terrainNoL)\n        : 1.0;\n    return input.terrainDirectDiffuse * shadow + input.terrainAmbientDiffuse;\n}\n'''
if old not in text:
    raise SystemExit('evaluateTerrainFast anchor changed')
text = text.replace(old, new, 1)

# One solar midpoint sample replaces the nested two-sample solar integral. This is still midpoint
# quadrature over the physical exponential density profile; the long-term production route is a
# Bruneton/Hillaire transmittance LUT, but this removes the dominant temporary per-pixel loop.
old = '''    // Runtime fast path: midpoint integration with two solar samples. The next renderer stage\n    // replaces this per-pixel integral with a precomputed transmittance LUT.\n    float stepLength = max(t1, 0.0) / 2.0;\n    float opticalDepth = 0.0;\n    [unroll]\n    for (int i = 0; i < 2; ++i)\n    {\n        float t = (i + 0.5) * stepLength;\n        opticalDepth += densityAtRadius(length(point + sunDir * t), groundRadius, scaleHeight) * stepLength;\n    }\n    return opticalDepth;'''
new = '''    // Single midpoint quadrature. The physical density law and exact atmosphere intersection are\n    // retained, while repeated full-screen solar integrations are eliminated.\n    float pathLength = max(t1, 0.0);\n    float midpointT = pathLength * 0.5;\n    return densityAtRadius(length(point + sunDir * midpointT), groundRadius, scaleHeight) * pathLength;'''
if old not in text:
    raise SystemExit('sun optical depth loop anchor changed')
text = text.replace(old, new, 1)

old = '''    float3 background = float3(0.00035, 0.00045, 0.00075) + proceduralStars(ray);'''
new = '''    float3 background = float3(0.00035, 0.00045, 0.00075);\n    // Stars are invisible through a daylight atmosphere. Avoid two hash fields and a high-order pow\n    // over the entire 1080p sky when the local sun is above twilight.\n    float cameraRadius = max(length(cameraPlanet), 1.0);\n    float localSunAltitude = dot(cameraPlanet / cameraRadius, sunDir);\n    float starVisibility = 1.0 - smoothstep(-0.12, 0.04, localSunAltitude);\n    if (starVisibility > 0.001) background += proceduralStars(ray) * starVisibility;'''
if old not in text:
    raise SystemExit('sky star anchor changed')
text = text.replace(old, new, 1)

# Replace the unconditional solar basis/plane work with a cheap angular dot-product gate.
old = '''    float sunAngularRadius = clamp(abs(gPush.data1.w), 0.0001, 1.45);\n    float3 helper = abs(sunDir.y) < 0.92 ? float3(0.0, 1.0, 0.0) : float3(1.0, 0.0, 0.0);\n    float3 sunRight = normalize(cross(helper, sunDir));\n    float3 sunUp = normalize(cross(sunDir, sunRight));\n    float sinRadius = max(sin(sunAngularRadius), 1.0e-5);\n    float2 solarPlane = float2(dot(ray, sunRight), dot(ray, sunUp)) / sinRadius;\n    float solarR = length(solarPlane);\n    // Corona FBM/atan/trigonometry used to execute for every full-screen pixel even though the\n    // result contributes only within 1.85 apparent solar radii. Keep identical art inside the mask.\n    if (!hitsGround && solarR < 1.85) {'''
new = '''    float sunAngularRadius = clamp(abs(gPush.data1.w), 0.0001, 1.45);\n    float2 solarPlane = float2(2.0, 2.0);\n    float solarR = 2.0;\n    float sunOuterCos = cos(min(sunAngularRadius * 1.86, 1.50));\n    float raySunCos = dot(ray, sunDir);\n    // Only the tiny angular region around the solar disc pays basis construction, sin, atan, FBM\n    // and granulation. All other sky pixels skip the complete solar surface shader.\n    if (!hitsGround && raySunCos > sunOuterCos)\n    {\n        float3 helper = abs(sunDir.y) < 0.92 ? float3(0.0, 1.0, 0.0) : float3(1.0, 0.0, 0.0);\n        float3 sunRight = normalize(cross(helper, sunDir));\n        float3 sunUp = normalize(cross(sunDir, sunRight));\n        float sinRadius = max(sin(sunAngularRadius), 1.0e-5);\n        solarPlane = float2(dot(ray, sunRight), dot(ray, sunUp)) / sinRadius;\n        solarR = length(solarPlane);\n    }\n    if (!hitsGround && solarR < 1.85) {'''
if old not in text:
    raise SystemExit('solar plane anchor changed')
text = text.replace(old, new, 1)

old = '''    // Four view samples x two sun samples instead of the old 8x4 nested integral. Coefficients,\n    // phase functions and midpoint integration stay physical; this is an immediate GPU rescue until\n    // the Hillaire-style Transmittance / MultipleScattering / SkyView / AerialPerspective LUT path.\n    float segment = (endT - startT) / 4.0;\n    float opticalView = 0.0;\n    float3 scattering = 0.0;\n    float3 transmittance = 1.0;\n    [unroll]\n    for (int i = 0; i < 4; ++i)\n    {\n        float t = startT + (i + 0.5) * segment;\n        float3 samplePoint = cameraPlanet + ray * t;\n        float density = densityAtRadius(length(samplePoint), groundRadius, scaleHeight);\n        float sunDepth = sunOpticalDepth(samplePoint, sunDir, atmosphereRadius, groundRadius, scaleHeight);\n        if (sunDepth > 1.0e7) continue;\n\n        opticalView += density * segment;\n        float3 extinction = betaR * (opticalView + sunDepth) + betaM * (opticalView + sunDepth);\n        float3 lightTransmittance = exp(-extinction);\n        float3 source = (betaR * rayleighPhase + betaM * miePhase) * density;\n        scattering += source * lightTransmittance * segment * gPush.data3.yzw;\n    }\n\n    transmittance = exp(-(betaR + betaM) * opticalView);'''
new = '''    // R24 throughput path: one view midpoint x one solar midpoint. This preserves exact ray/sphere\n    // bounds, exponential density, Rayleigh/Mie coefficients and phase functions while reducing the\n    // temporary 4x2 nested quadrature to one sample. Bruneton/Hillaire LUTs are the next fidelity\n    // upgrade; until then a deterministic single midpoint is preferable to blowing the frame budget.\n    float segment = endT - startT;\n    float t = startT + segment * 0.5;\n    float3 samplePoint = cameraPlanet + ray * t;\n    float density = densityAtRadius(length(samplePoint), groundRadius, scaleHeight);\n    float sunDepth = sunOpticalDepth(samplePoint, sunDir, atmosphereRadius, groundRadius, scaleHeight);\n    float opticalView = density * segment;\n    float3 scattering = 0.0;\n    if (sunDepth <= 1.0e7)\n    {\n        float3 extinction = (betaR + betaM) * (opticalView * 0.5 + sunDepth);\n        float3 lightTransmittance = exp(-extinction);\n        float3 source = (betaR * rayleighPhase + betaM * miePhase) * density;\n        scattering = source * lightTransmittance * segment * gPush.data3.yzw;\n    }\n\n    float3 transmittance = exp(-(betaR + betaM) * opticalView);'''
if old not in text:
    raise SystemExit('sky view integration anchor changed')
text = text.replace(old, new, 1)

shader_path.write_text(text, encoding='utf-8')
print('R24 shader throughput rescue materialized')
