#pragma once

#include "vf/world/PlanetSurface.hpp"

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <queue>
#include <stdexcept>
#include <utility>
#include <vector>

#include <glm/geometric.hpp>

namespace vf {

struct RegionalHydrologyConfig {
    std::uint32_t resolution{129U};
    double halfExtentMeters{90000.0};
    double maxIncisionMeters{260.0};
    double riverHeadAccumulationFraction{0.0020};
    double fullChannelAccumulationFraction{0.050};
};

struct RegionalHydrologySample {
    double filledElevationMeters{};
    double contributingAreaFraction{};
    double channelStrength{};
    double incisionMeters{};
    double depositionPotential{};
    double lakePotential{};
};

// Deterministic local DEM hydrology authority. This is intentionally a regional bake rather than a
// pointwise noise mask: every cell drains through an explicit downstream topology generated by a
// Priority-Flood traversal. Reverse traversal then accumulates contributing area, so river strength
// is a consequence of drainage and cannot run uphill. The algorithm is game-budgeted but follows
// mature DEM hydrology practice closely enough to serve as the authority layer for rivers/canyons.
class RegionalHydrology final {
public:
    RegionalHydrology() = default;

    RegionalHydrology(
        const PlanetDefinition& planet,
        const glm::dvec3& centerDirection,
        RegionalHydrologyConfig config = {}) {
        rebuild(planet, centerDirection, config);
    }

    void rebuild(
        const PlanetDefinition& planet,
        const glm::dvec3& centerDirection,
        RegionalHydrologyConfig config = {}) {
        config_ = config;
        config_.resolution = std::clamp<std::uint32_t>(config_.resolution, 17U, 513U);
        if ((config_.resolution & 1U) == 0U) ++config_.resolution;
        if (!std::isfinite(config_.halfExtentMeters) || config_.halfExtentMeters <= 100.0) {
            config_.halfExtentMeters = 90000.0;
        }
        if (!std::isfinite(config_.maxIncisionMeters) || config_.maxIncisionMeters < 0.0) {
            config_.maxIncisionMeters = 0.0;
        }
        config_.riverHeadAccumulationFraction = std::clamp(
            config_.riverHeadAccumulationFraction, 1.0e-7, 0.95);
        config_.fullChannelAccumulationFraction = std::clamp(
            config_.fullChannelAccumulationFraction,
            config_.riverHeadAccumulationFraction + 1.0e-7,
            1.0);

        planet_ = planet;
        center_ = safeNormalize(centerDirection, {0.0, 1.0, 0.0});
        east_ = tangentAxis(center_);
        north_ = safeNormalize(glm::cross(center_, east_), {0.0, 0.0, 1.0});
        cellSizeMeters_ = 2.0 * config_.halfExtentMeters
            / static_cast<double>(config_.resolution - 1U);

        const std::size_t count = static_cast<std::size_t>(config_.resolution)
            * static_cast<std::size_t>(config_.resolution);
        elevation_.assign(count, 0.0);
        filled_.assign(count, 0.0);
        downstream_.assign(count, kNoCell);
        accumulation_.assign(count, 1.0);
        visitOrder_.clear();
        visitOrder_.reserve(count);

        for (std::uint32_t y = 0; y < config_.resolution; ++y) {
            const double northMeters = coordinateMeters(y);
            for (std::uint32_t x = 0; x < config_.resolution; ++x) {
                const double eastMeters = coordinateMeters(x);
                const glm::dvec3 direction = directionAt(eastMeters, northMeters);
                elevation_[index(x, y)] = samplePlanetTerrain(planet_, direction).elevationMeters;
            }
        }

        priorityFlood();
        accumulateDrainage();
    }

    [[nodiscard]] bool empty() const noexcept { return elevation_.empty(); }
    [[nodiscard]] std::uint32_t resolution() const noexcept { return config_.resolution; }
    [[nodiscard]] double halfExtentMeters() const noexcept { return config_.halfExtentMeters; }
    [[nodiscard]] double cellSizeMeters() const noexcept { return cellSizeMeters_; }
    [[nodiscard]] const glm::dvec3& centerDirection() const noexcept { return center_; }

    [[nodiscard]] RegionalHydrologySample sample(const glm::dvec3& direction) const noexcept {
        if (empty()) return {};
        const glm::dvec3 d = safeNormalize(direction, center_);
        const double denom = std::max(1.0e-12, glm::dot(d, center_));
        const double eastMeters = planet_.radius * glm::dot(d, east_) / denom;
        const double northMeters = planet_.radius * glm::dot(d, north_) / denom;
        return sampleLocal(eastMeters, northMeters);
    }

    [[nodiscard]] RegionalHydrologySample sampleLocal(
        double eastMeters,
        double northMeters) const noexcept {
        if (empty()) return {};
        const double gx = (eastMeters + config_.halfExtentMeters) / cellSizeMeters_;
        const double gy = (northMeters + config_.halfExtentMeters) / cellSizeMeters_;
        if (gx < 0.0 || gy < 0.0
            || gx > static_cast<double>(config_.resolution - 1U)
            || gy > static_cast<double>(config_.resolution - 1U)) {
            return {};
        }

        const std::uint32_t x0 = static_cast<std::uint32_t>(std::floor(gx));
        const std::uint32_t y0 = static_cast<std::uint32_t>(std::floor(gy));
        const std::uint32_t x1 = std::min(x0 + 1U, config_.resolution - 1U);
        const std::uint32_t y1 = std::min(y0 + 1U, config_.resolution - 1U);
        const double tx = gx - static_cast<double>(x0);
        const double ty = gy - static_cast<double>(y0);

        const RegionalHydrologySample s00 = cellSample(x0, y0);
        const RegionalHydrologySample s10 = cellSample(x1, y0);
        const RegionalHydrologySample s01 = cellSample(x0, y1);
        const RegionalHydrologySample s11 = cellSample(x1, y1);
        return bilerp(s00, s10, s01, s11, tx, ty);
    }

    [[nodiscard]] double displacedElevationMeters(const glm::dvec3& direction) const noexcept {
        const double base = samplePlanetTerrain(planet_, safeNormalize(direction, center_)).elevationMeters;
        const RegionalHydrologySample hydro = sample(direction);
        return base - hydro.incisionMeters;
    }

private:
    static constexpr std::size_t kNoCell = std::numeric_limits<std::size_t>::max();

    struct QueueNode {
        double elevation{};
        std::size_t cell{};
        std::uint64_t sequence{};
    };

    struct QueueCompare {
        bool operator()(const QueueNode& a, const QueueNode& b) const noexcept {
            if (a.elevation != b.elevation) return a.elevation > b.elevation;
            return a.sequence > b.sequence;
        }
    };

    [[nodiscard]] static glm::dvec3 safeNormalize(
        const glm::dvec3& value,
        const glm::dvec3& fallback) noexcept {
        const double l2 = glm::dot(value, value);
        return l2 > 1.0e-18 ? value / std::sqrt(l2) : fallback;
    }

    [[nodiscard]] static glm::dvec3 tangentAxis(const glm::dvec3& upInput) noexcept {
        const glm::dvec3 up = safeNormalize(upInput, {0.0, 1.0, 0.0});
        const glm::dvec3 a = glm::abs(up);
        glm::dvec3 reference{1.0, 0.0, 0.0};
        if (a.y <= a.x && a.y <= a.z) reference = {0.0, 1.0, 0.0};
        else if (a.z <= a.x && a.z <= a.y) reference = {0.0, 0.0, 1.0};
        return safeNormalize(glm::cross(reference, up), {1.0, 0.0, 0.0});
    }

    [[nodiscard]] static double smooth01(double edge0, double edge1, double value) noexcept {
        if (edge1 <= edge0) return value >= edge1 ? 1.0 : 0.0;
        const double x = std::clamp((value - edge0) / (edge1 - edge0), 0.0, 1.0);
        return x * x * (3.0 - 2.0 * x);
    }

    [[nodiscard]] std::size_t index(std::uint32_t x, std::uint32_t y) const noexcept {
        return static_cast<std::size_t>(y) * config_.resolution + x;
    }

    [[nodiscard]] double coordinateMeters(std::uint32_t coordinate) const noexcept {
        return -config_.halfExtentMeters + static_cast<double>(coordinate) * cellSizeMeters_;
    }

    [[nodiscard]] glm::dvec3 directionAt(double eastMeters, double northMeters) const noexcept {
        return safeNormalize(
            center_ + east_ * (eastMeters / planet_.radius)
                + north_ * (northMeters / planet_.radius),
            center_);
    }

    void priorityFlood() {
        const std::size_t count = elevation_.size();
        std::vector<std::uint8_t> visited(count, 0U);
        std::priority_queue<QueueNode, std::vector<QueueNode>, QueueCompare> queue;
        std::uint64_t sequence = 0U;

        const auto pushBoundary = [&](std::uint32_t x, std::uint32_t y) {
            const std::size_t cell = index(x, y);
            if (visited[cell] != 0U) return;
            visited[cell] = 1U;
            filled_[cell] = elevation_[cell];
            downstream_[cell] = kNoCell;
            queue.push({filled_[cell], cell, sequence++});
        };

        for (std::uint32_t x = 0; x < config_.resolution; ++x) {
            pushBoundary(x, 0U);
            pushBoundary(x, config_.resolution - 1U);
        }
        for (std::uint32_t y = 1U; y + 1U < config_.resolution; ++y) {
            pushBoundary(0U, y);
            pushBoundary(config_.resolution - 1U, y);
        }

        static constexpr int dx[8] = {-1, 0, 1, -1, 1, -1, 0, 1};
        static constexpr int dy[8] = {-1, -1, -1, 0, 0, 1, 1, 1};

        while (!queue.empty()) {
            const QueueNode current = queue.top();
            queue.pop();
            visitOrder_.push_back(current.cell);
            const std::uint32_t cx = static_cast<std::uint32_t>(current.cell % config_.resolution);
            const std::uint32_t cy = static_cast<std::uint32_t>(current.cell / config_.resolution);

            for (int n = 0; n < 8; ++n) {
                const int nx = static_cast<int>(cx) + dx[n];
                const int ny = static_cast<int>(cy) + dy[n];
                if (nx < 0 || ny < 0
                    || nx >= static_cast<int>(config_.resolution)
                    || ny >= static_cast<int>(config_.resolution)) {
                    continue;
                }
                const std::size_t neighbor = index(
                    static_cast<std::uint32_t>(nx),
                    static_cast<std::uint32_t>(ny));
                if (visited[neighbor] != 0U) continue;
                visited[neighbor] = 1U;
                filled_[neighbor] = std::max(elevation_[neighbor], current.elevation);
                downstream_[neighbor] = current.cell;
                queue.push({filled_[neighbor], neighbor, sequence++});
            }
        }
    }

    void accumulateDrainage() {
        std::fill(accumulation_.begin(), accumulation_.end(), 1.0);
        for (auto it = visitOrder_.rbegin(); it != visitOrder_.rend(); ++it) {
            const std::size_t cell = *it;
            const std::size_t downstream = downstream_[cell];
            if (downstream != kNoCell) accumulation_[downstream] += accumulation_[cell];
        }
    }

    [[nodiscard]] RegionalHydrologySample cellSample(
        std::uint32_t x,
        std::uint32_t y) const noexcept {
        const std::size_t cell = index(x, y);
        const double count = static_cast<double>(elevation_.size());
        const double areaFraction = std::clamp(accumulation_[cell] / count, 0.0, 1.0);
        const double channel = smooth01(
            config_.riverHeadAccumulationFraction,
            config_.fullChannelAccumulationFraction,
            areaFraction);

        const std::size_t downstream = downstream_[cell];
        double slope = 0.0;
        if (downstream != kNoCell) {
            const std::uint32_t dx = static_cast<std::uint32_t>(downstream % config_.resolution);
            const std::uint32_t dy = static_cast<std::uint32_t>(downstream / config_.resolution);
            const int ix = static_cast<int>(dx) - static_cast<int>(x);
            const int iy = static_cast<int>(dy) - static_cast<int>(y);
            const double distance = cellSizeMeters_ * ((ix != 0 && iy != 0) ? std::sqrt(2.0) : 1.0);
            slope = std::max(0.0, filled_[cell] - filled_[downstream]) / std::max(1.0, distance);
        }
        const double slopeResponse = smooth01(0.0008, 0.075, slope);
        const double incision = config_.maxIncisionMeters * channel
            * (0.22 + 0.78 * slopeResponse);
        const double flatness = 1.0 - smooth01(0.0010, 0.015, slope);
        const double deposition = channel * flatness;
        const double depressionDepth = std::max(0.0, filled_[cell] - elevation_[cell]);
        const double lake = smooth01(0.5, 12.0, depressionDepth) * flatness;
        return {
            filled_[cell],
            areaFraction,
            channel,
            incision,
            deposition,
            lake,
        };
    }

    [[nodiscard]] static RegionalHydrologySample bilerp(
        const RegionalHydrologySample& s00,
        const RegionalHydrologySample& s10,
        const RegionalHydrologySample& s01,
        const RegionalHydrologySample& s11,
        double tx,
        double ty) noexcept {
        const auto blend = [&](double a00, double a10, double a01, double a11) {
            const double ax0 = a00 + (a10 - a00) * tx;
            const double ax1 = a01 + (a11 - a01) * tx;
            return ax0 + (ax1 - ax0) * ty;
        };
        return {
            blend(s00.filledElevationMeters, s10.filledElevationMeters,
                s01.filledElevationMeters, s11.filledElevationMeters),
            blend(s00.contributingAreaFraction, s10.contributingAreaFraction,
                s01.contributingAreaFraction, s11.contributingAreaFraction),
            blend(s00.channelStrength, s10.channelStrength,
                s01.channelStrength, s11.channelStrength),
            blend(s00.incisionMeters, s10.incisionMeters,
                s01.incisionMeters, s11.incisionMeters),
            blend(s00.depositionPotential, s10.depositionPotential,
                s01.depositionPotential, s11.depositionPotential),
            blend(s00.lakePotential, s10.lakePotential,
                s01.lakePotential, s11.lakePotential),
        };
    }

    PlanetDefinition planet_{};
    RegionalHydrologyConfig config_{};
    glm::dvec3 center_{0.0, 1.0, 0.0};
    glm::dvec3 east_{1.0, 0.0, 0.0};
    glm::dvec3 north_{0.0, 0.0, 1.0};
    double cellSizeMeters_{};
    std::vector<double> elevation_;
    std::vector<double> filled_;
    std::vector<std::size_t> downstream_;
    std::vector<double> accumulation_;
    std::vector<std::size_t> visitOrder_;
};

} // namespace vf
