# CMake generated Testfile for 
# Source directory: /home/runner/work/voxel-frontier/voxel-frontier/native
# Build directory: /home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[vf_planet_physics_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_planet_physics_tests")
set_tests_properties([=[vf_planet_physics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;212;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_terrain_landform_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_terrain_landform_tests")
set_tests_properties([=[vf_terrain_landform_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;215;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_camera_input_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_camera_input_tests")
set_tests_properties([=[vf_camera_input_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;218;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_character_controller_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_character_controller_tests")
set_tests_properties([=[vf_character_controller_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;221;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_collision_geometry_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_collision_geometry_tests")
set_tests_properties([=[vf_collision_geometry_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;224;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_convex_hull_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_convex_hull_tests")
set_tests_properties([=[vf_convex_hull_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;227;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_gjk_epa_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_gjk_epa_tests")
set_tests_properties([=[vf_gjk_epa_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;230;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_contact_solver_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_contact_solver_tests")
set_tests_properties([=[vf_contact_solver_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;233;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_mechanics_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_mechanics_tests")
set_tests_properties([=[vf_mechanics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;236;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_physics_mesh_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_physics_mesh_tests")
set_tests_properties([=[vf_physics_mesh_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;239;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_celestial_system_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_celestial_system_tests")
set_tests_properties([=[vf_celestial_system_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;242;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_celestial_physics_frame_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_celestial_physics_frame_tests")
set_tests_properties([=[vf_celestial_physics_frame_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;245;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_celestial_surface_frames_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_celestial_surface_frames_tests")
set_tests_properties([=[vf_celestial_surface_frames_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;248;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_interplanetary_flight_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_interplanetary_flight_tests")
set_tests_properties([=[vf_interplanetary_flight_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;251;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_gameplay_interaction_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_gameplay_interaction_tests")
set_tests_properties([=[vf_gameplay_interaction_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;254;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_sparse_universe_catalog_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_sparse_universe_catalog_tests")
set_tests_properties([=[vf_sparse_universe_catalog_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;257;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_spectral_optics_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_spectral_optics_tests")
set_tests_properties([=[vf_spectral_optics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;260;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_electromagnetic_radiation_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_electromagnetic_radiation_tests")
set_tests_properties([=[vf_electromagnetic_radiation_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;263;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_material_physics_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_material_physics_tests")
set_tests_properties([=[vf_material_physics_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;266;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_gas_volume_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_gas_volume_tests")
set_tests_properties([=[vf_gas_volume_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;269;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_rope_xpbd_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_rope_xpbd_tests")
set_tests_properties([=[vf_rope_xpbd_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;272;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_structural_damage_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_structural_damage_tests")
set_tests_properties([=[vf_structural_damage_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;275;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
add_test([=[vf_r24_physical_planet_tests]=] "/home/runner/work/voxel-frontier/voxel-frontier/native/build-r24-core/vf_r24_physical_planet_tests")
set_tests_properties([=[vf_r24_physical_planet_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;278;add_test;/home/runner/work/voxel-frontier/voxel-frontier/native/CMakeLists.txt;0;")
subdirs("_deps/glm-build")
