if(NOT DEFINED VERT OR NOT DEFINED OPAQUE_FRAG OR NOT DEFINED TRANSPARENT_FRAG OR NOT DEFINED SHADOW_VERT OR NOT DEFINED SHADOW_FRAG OR NOT DEFINED FULLSCREEN_VERT OR NOT DEFINED SKY_FRAG OR NOT DEFINED HUD_FRAG OR NOT DEFINED OUT)
    message(FATAL_ERROR "All production shader stage paths and OUT are required")
endif()

function(read_spirv INPUT OUTPUT_VAR)
    file(READ "${INPUT}" HEX_DATA HEX)
    string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," BYTE_DATA "${HEX_DATA}")
    set(${OUTPUT_VAR} "${BYTE_DATA}" PARENT_SCOPE)
endfunction()

read_spirv("${VERT}" VERT_BYTES)
read_spirv("${OPAQUE_FRAG}" OPAQUE_FRAG_BYTES)
read_spirv("${TRANSPARENT_FRAG}" TRANSPARENT_FRAG_BYTES)
read_spirv("${SHADOW_VERT}" SHADOW_VERT_BYTES)
read_spirv("${SHADOW_FRAG}" SHADOW_FRAG_BYTES)
read_spirv("${FULLSCREEN_VERT}" FULLSCREEN_VERT_BYTES)
read_spirv("${SKY_FRAG}" SKY_FRAG_BYTES)
read_spirv("${HUD_FRAG}" HUD_FRAG_BYTES)

file(WRITE "${OUT}" "#pragma once\n#include <cstddef>\n\nnamespace vf::shaders {\n")
foreach(NAME IN ITEMS PlanetVertex OpaqueFragment TransparentFragment ShadowVertex ShadowFragment FullscreenVertex SkyFragment HudFragment)
    if(NAME STREQUAL "PlanetVertex")
        set(BYTES "${VERT_BYTES}")
    elseif(NAME STREQUAL "OpaqueFragment")
        set(BYTES "${OPAQUE_FRAG_BYTES}")
    elseif(NAME STREQUAL "TransparentFragment")
        set(BYTES "${TRANSPARENT_FRAG_BYTES}")
    elseif(NAME STREQUAL "ShadowVertex")
        set(BYTES "${SHADOW_VERT_BYTES}")
    elseif(NAME STREQUAL "ShadowFragment")
        set(BYTES "${SHADOW_FRAG_BYTES}")
    elseif(NAME STREQUAL "FullscreenVertex")
        set(BYTES "${FULLSCREEN_VERT_BYTES}")
    elseif(NAME STREQUAL "SkyFragment")
        set(BYTES "${SKY_FRAG_BYTES}")
    else()
        set(BYTES "${HUD_FRAG_BYTES}")
    endif()
    file(APPEND "${OUT}" "alignas(4) inline constexpr unsigned char k${NAME}Spv[] = {${BYTES}};\n")
    file(APPEND "${OUT}" "inline constexpr std::size_t k${NAME}SpvSize = sizeof(k${NAME}Spv);\n")
endforeach()
file(APPEND "${OUT}" "}\n")
