if(NOT DEFINED VERT OR NOT DEFINED FRAG OR NOT DEFINED SHADOW_VERT OR NOT DEFINED SHADOW_FRAG OR NOT DEFINED OUT)
    message(FATAL_ERROR "VERT, FRAG, SHADOW_VERT, SHADOW_FRAG and OUT are required")
endif()

file(READ "${VERT}" VERT_HEX HEX)
file(READ "${FRAG}" FRAG_HEX HEX)
file(READ "${SHADOW_VERT}" SHADOW_VERT_HEX HEX)
file(READ "${SHADOW_FRAG}" SHADOW_FRAG_HEX HEX)
string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," VERT_BYTES "${VERT_HEX}")
string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," FRAG_BYTES "${FRAG_HEX}")
string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," SHADOW_VERT_BYTES "${SHADOW_VERT_HEX}")
string(REGEX REPLACE "([0-9A-Fa-f][0-9A-Fa-f])" "0x\\1," SHADOW_FRAG_BYTES "${SHADOW_FRAG_HEX}")

file(WRITE "${OUT}" "#pragma once\n#include <cstddef>\n\nnamespace vf::shaders {\n")
file(APPEND "${OUT}" "alignas(4) inline constexpr unsigned char kPlanetVertexSpv[] = {${VERT_BYTES}};\n")
file(APPEND "${OUT}" "inline constexpr std::size_t kPlanetVertexSpvSize = sizeof(kPlanetVertexSpv);\n")
file(APPEND "${OUT}" "alignas(4) inline constexpr unsigned char kPlanetFragmentSpv[] = {${FRAG_BYTES}};\n")
file(APPEND "${OUT}" "inline constexpr std::size_t kPlanetFragmentSpvSize = sizeof(kPlanetFragmentSpv);\n")
file(APPEND "${OUT}" "alignas(4) inline constexpr unsigned char kShadowVertexSpv[] = {${SHADOW_VERT_BYTES}};\n")
file(APPEND "${OUT}" "inline constexpr std::size_t kShadowVertexSpvSize = sizeof(kShadowVertexSpv);\n")
file(APPEND "${OUT}" "alignas(4) inline constexpr unsigned char kShadowFragmentSpv[] = {${SHADOW_FRAG_BYTES}};\n")
file(APPEND "${OUT}" "inline constexpr std::size_t kShadowFragmentSpvSize = sizeof(kShadowFragmentSpv);\n")
file(APPEND "${OUT}" "}\n")
